export { default as Table } from "./table.svelte"
export { default as Tbody } from "./tbody.svelte"
export { default as Td } from "./td.svelte"
export { default as Tfoot } from "./tfoot.svelte"
export { default as Th } from "./th.svelte"
export { default as Thead } from "./thead.svelte"
export { default as Tr } from "./tr.svelte"
